runs:
  using: docker
  image: 'Dockerfile'
  env:
    # May the the docker image
    OPENAI_API_KEY: ${{ inputs.openai-key }}
    
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    PR_NUMBER: ${{ github.event.pull_request.number }}
    GITHUB_REPOSITORY: ${{ github.repository }}
