name: 'AI Code Reviewer'
description: 'Automated code review using AI'
branding:
  icon: 'robot'
  color: 'blue'

inputs:
  openai-key:
    description: 'OpenAI API key'
    required: true
  model:
    description: 'OpenAI model to use'
    default: 'gpt-4-turbo-preview'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
